INSERT INTO Users (username, email, password_hash) VALUES
('john_doe', 'john.doe@example.com', 'hashed_password_1'),
('jane_smith', 'jane.smith@example.com', 'hashed_password_2'),
('mike_jones', 'mike.jones@example.com', 'hashed_password_3'),
('lisa_taylor', 'lisa.taylor@example.com', 'hashed_password_4'),
('emily_clark', 'emily.clark@example.com', 'hashed_password_5');

INSERT INTO Recipes (name, user_id, description, image_url, preparation_time, cooking_time) VALUES
('Chicken Alfredo',1, 'Creamy pasta with grilled chicken and Alfredo sauce.', 'https://example.com/images/chickenalfredo.jpg', 15, 25),
('Greek Salad',2, 'Fresh salad with tomatoes, cucumbers, olives, and feta cheese.', 'https://example.com/images/greeksalad.jpg', 10, 0),
('Beef Stroganoff',3, 'Tender beef in a creamy mushroom sauce served over noodles.', 'https://example.com/images/beefstroganoff.jpg', 20, 45),
('Classic Tacos',4, 'Ground beef tacos with your choice of toppings.', 'https://example.com/images/classictacos.jpg', 15, 10),
('Margherita Pizza',5, 'Simple pizza with tomato sauce, mozzarella cheese, and fresh basil.', 'https://example.com/images/margheritapizza.jpg', 20, 15),
('Pancakes',1, 'Fluffy pancakes served with syrup and butter.', 'https://example.com/images/pancakes.jpg', 10, 10),
('Sushi Rolls',2, 'Homemade sushi rolls with fresh fish and vegetables.', 'https://example.com/images/sushirolls.jpg', 30, 15),
('Stir-Fried Vegetables',3, 'Colorful stir-fried vegetables with soy sauce and garlic.', 'https://example.com/images/stirfriedvegetables.jpg', 15, 10),
('Chocolate Cake',4, 'Rich chocolate cake with chocolate frosting.', 'https://example.com/images/chocolatecake.jpg', 20, 30),
('BBQ Ribs',5, 'Tender ribs coated in BBQ sauce and baked to perfection.', 'https://example.com/images/bbqribs.jpg', 20, 120),
('Greek Salad',1, 'A refreshing salad with cucumbers, tomatoes, olives, and feta cheese.', 'https://example.com/images/greeksalad.jpg', 10, 0),
('Lemon Garlic Chicken',2, 'Grilled chicken marinated in lemon and garlic.', 'https://example.com/images/lemongarlicchicken.jpg', 15, 20),
('Fish Tacos',3, 'Light and fresh fish tacos with a zesty sauce.', 'https://example.com/images/fishtacos.jpg', 20, 15),
('Eggplant Parmesan',4, 'Layers of breaded eggplant with marinara sauce and cheese.', 'https://example.com/images/eggplantparmesan.jpg', 30, 60),
('Teriyaki Chicken',5, 'Chicken marinated in teriyaki sauce and grilled.', 'https://example.com/images/teriyakichicken.jpg', 20, 20),
('Lasagna',1, 'Classic Italian lasagna with layers of meat sauce, cheese, and noodles.', 'https://example.com/images/lasagna.jpg', 30, 60),
('Caprese Salad',2, 'Tomato and mozzarella salad with fresh basil.', 'https://example.com/images/capresesalad.jpg', 10, 0),
('Pad Thai',3, 'Thai stir-fried noodles with shrimp and vegetables.', 'https://example.com/images/padthai.jpg', 20, 15),
('Baked Salmon',4, 'Salmon fillets baked with lemon and dill.', 'https://example.com/images/bakedsalmon.jpg', 15, 20),
('Banana Bread',5, 'Moist banana bread with a hint of cinnamon.', 'https://example.com/images/bananabread.jpg', 15, 60),
('Chicken Curry',1, 'Spicy chicken curry served over rice.', 'https://example.com/images/chickencurry.jpg', 20, 30),
('Tom Yum Soup',2, 'Thai soup with shrimp, mushrooms, and a spicy broth.', 'https://example.com/images/tomyumsoup.jpg', 15, 20),
('Falafel',3, 'Spiced chickpea balls served with tahini sauce.', 'https://example.com/images/falafel.jpg', 20, 30),
('Beef Stroganoff',4, 'Creamy beef stroganoff with mushrooms served over egg noodles.', 'https://example.com/images/beefstroganoff.jpg', 20, 45),
('Mushroom Risotto',5, 'Creamy risotto with sautéed mushrooms and Parmesan cheese.', 'https://example.com/images/mushroomrisotto.jpg', 25, 40),
('Chicken Fajitas',1, 'Grilled chicken with peppers and onions served with tortillas.', 'https://example.com/images/chickenfajitas.jpg', 20, 15),
('Cornbread',2, 'Sweet and moist cornbread served as a side dish.', 'https://example.com/images/cornbread.jpg', 10, 25),
('Quiche Lorraine',3, 'Savory pie with bacon, cheese, and eggs.', 'https://example.com/images/quichelorraine.jpg', 20, 45),
('Peking Duck',4, 'Roasted duck with a crispy skin and savory sauce.', 'https://example.com/images/pekingduck.jpg', 60, 90),
('Apple Pie',5, 'Classic apple pie with a flaky crust and spiced apples.', 'https://example.com/images/applepie.jpg', 30, 60);

INSERT INTO Ingredients (recipe_id, name, quantity) VALUES
(1, 'Fettuccine', '12 oz'),
(1, 'Chicken Breast', '2 pieces'),
(1, 'Alfredo Sauce', '1 cup'),
(2, 'Romaine Lettuce', '1 head'),
(2, 'Cherry Tomatoes', '1 cup'),
(2, 'Cucumber', '1'),
(2, 'Kalamata Olives', '1/2 cup'),
(2, 'Feta Cheese', '1/2 cup'),
(3, 'Beef Sirloin', '1 lb'),
(3, 'Mushrooms', '8 oz'),
(3, 'Onion', '1'),
(3, 'Sour Cream', '1 cup'),
(3, 'Beef Broth', '1 cup'),
(4, 'Ground Beef', '1 lb'),
(4, 'Taco Shells', '8'),
(4, 'Lettuce', '1 head'),
(4, 'Cheddar Cheese', '1 cup'),
(4, 'Tomato', '1'),
(5, 'Pizza Dough', '1 lb'),
(5, 'Tomato Sauce', '1/2 cup'),
(5, 'Mozzarella Cheese', '1 cup'),
(5, 'Fresh Basil', '1/4 cup'),
(6, 'All-Purpose Flour', '1 cup'),
(6, 'Milk', '1 cup'),
(6, 'Eggs', '2'),
(6, 'Baking Powder', '2 tsp'),
(6, 'Sugar', '2 tbsp'),
(7, 'Sushi Rice', '2 cups'),
(7, 'Nori Sheets', '10'),
(7, 'Fresh Tuna', '1/2 lb'),
(7, 'Cucumber', '1'),
(7, 'Avocado', '1'),
(8, 'Bell Peppers', '2'),
(8, 'Broccoli', '1 cup'),
(8, 'Carrots', '1 cup'),
(8, 'Soy Sauce', '2 tbsp'),
(8, 'Garlic', '2 cloves'),
(9, 'All-Purpose Flour', '1 cup'),
(9, 'Cocoa Powder', '1/2 cup'),
(9, 'Sugar', '1 cup'),
(9, 'Eggs', '3'),
(9, 'Butter', '1/2 cup'),
(10, 'Pork Ribs', '2 lbs'),
(10, 'BBQ Sauce', '1 cup'),
(10, 'Garlic Powder', '1 tsp'),
(10, 'Paprika', '1 tsp'),
(11, 'Cucumber', '1'),
(11, 'Cherry Tomatoes', '1 cup'),
(11, 'Kalamata Olives', '1/2 cup'),
(11, 'Feta Cheese', '1/2 cup'),
(12, 'Chicken Breast', '2 pieces'),
(12, 'Lemon Juice', '2 tbsp'),
(12, 'Garlic', '3 cloves'),
(12, 'Olive Oil', '2 tbsp'),
(13, 'White Fish', '1 lb'),
(13, 'Taco Shells', '8'),
(13, 'Cabbage', '1 cup'),
(13, 'Lime Juice', '1 tbsp'),
(13, 'Cilantro', '1/4 cup'),
(14, 'Eggplant', '2 large'),
(14, 'Marinara Sauce', '2 cups'),
(14, 'Mozzarella Cheese', '1 cup'),
(14, 'Parmesan Cheese', '1/2 cup'),
(15, 'Chicken Thighs', '2 pieces'),
(15, 'Teriyaki Sauce', '1/4 cup'),
(15, 'Sesame Seeds', '1 tbsp'),
(16, 'Ground Beef', '1 lb'),
(16, 'Marinara Sauce', '2 cups'),
(16, 'Ricotta Cheese', '1 cup'),
(16, 'Mozzarella Cheese', '2 cups'),
(16, 'Lasagna Noodles', '12'),
(17, 'Tomatoes', '2'),
(17, 'Fresh Mozzarella', '8 oz'),
(17, 'Basil Leaves', '1/4 cup'),
(18, 'Rice Noodles', '8 oz'),
(18, 'Shrimp', '1/2 lb'),
(18, 'Bean Sprouts', '1 cup'),
(18, 'Fish Sauce', '2 tbsp'),
(18, 'Tamarind Paste', '1 tbsp'),
(19, 'Salmon Fillets', '2 pieces'),
(19, 'Lemon', '1'),
(19, 'Dill', '1 tbsp'),
(20, 'Bananas', '3 ripe'),
(20, 'All-Purpose Flour', '1 1/2 cups'),
(20, 'Sugar', '1 cup'),
(20, 'Butter', '1/2 cup'),
(20, 'Baking Soda', '1 tsp'),
(21, 'Chicken Breast', '2 pieces'),
(21, 'Curry Powder', '2 tbsp'),
(21, 'Coconut Milk', '1 can'),
(21, 'Rice', '1 cup'),
(22, 'Shrimp', '1/2 lb'),
(22, 'Mushrooms', '1 cup'),
(22, 'Lemongrass', '2 stalks'),
(22, 'Fish Sauce', '2 tbsp'),
(22, 'Chili Paste', '1 tbsp'),
(23, 'Chickpeas', '1 can'),
(23, 'Tahini', '1/4 cup'),
(23, 'Garlic', '2 cloves'),
(23, 'Cumin', '1 tsp'),
(24, 'Beef Sirloin', '1 lb'),
(24, 'Mushrooms', '8 oz'),
(24, 'Onion', '1'),
(24, 'Sour Cream', '1 cup'),
(24, 'Beef Broth', '1 cup'),
(25, 'Arborio Rice', '1 cup'),
(25, 'Mushrooms', '8 oz'),
(25, 'Chicken Broth', '4 cups'),
(25, 'Parmesan Cheese', '1/2 cup'),
(26, 'Chicken Breast', '2 pieces'),
(26, 'Bell Peppers', '2'),
(26, 'Onion', '1'),
(26, 'Tortillas', '8'),
(26, 'Fajita Seasoning', '2 tbsp'),
(27, 'Cornmeal', '1 cup'),
(27, 'Flour', '1 cup'),
(27, 'Sugar', '1/4 cup'),
(27, 'Baking Powder', '2 tsp'),
(27, 'Milk', '1 cup'),
(28, 'Pie Crust', '1'),
(28, 'Apples', '4 cups, peeled and sliced'),
(28, 'Sugar', '1/2 cup'),
(28, 'Cinnamon', '1 tsp'),
(28, 'Butter', '1/4 cup'),
(29, 'Duck', '1 whole'),
(29, 'Peking Duck Sauce', '1 cup'),
(30, 'Pie Crust', '1'),
(30, 'Apples', '4 cups, peeled and sliced'),
(30, 'Sugar', '1 cup'),
(30, 'Cinnamon', '1 tsp'),
(30, 'Butter', '1/4 cup');

INSERT INTO RecipeSteps (recipe_id, step_number, instruction) VALUES
(1, 1, 'Cook fettuccine according to package instructions.'),
(1, 2, 'Season and grill chicken breasts until fully cooked.'),
(1, 3, 'Toss cooked pasta with Alfredo sauce and sliced chicken.'),
(2, 1, 'Chop romaine lettuce and slice cherry tomatoes and cucumber.'),
(2, 2, 'Combine lettuce, tomatoes, cucumber, olives, and feta cheese in a bowl.'),
(2, 3, 'Toss with olive oil and season with salt and pepper.'),
(3, 1, 'Cut beef sirloin into thin strips and brown in a pan.'),
(3, 2, 'Add sliced mushrooms and diced onion, cooking until tender.'),
(3, 3, 'Stir in sour cream and beef broth, simmer until thickened.'),
(4, 1, 'Brown ground beef in a skillet, then drain excess fat.'),
(4, 2, 'Add taco seasoning and water, simmer until thickened.'),
(4, 3, 'Fill taco shells with beef mixture and desired toppings.'),
(5, 1, 'Preheat oven to 475°F.'),
(5, 2, 'Roll out pizza dough on a floured surface.'),
(5, 3, 'Spread tomato sauce over dough and top with mozzarella cheese and basil.'),
(5, 4, 'Bake for 12-15 minutes until crust is golden and cheese is melted.'),
(6, 1, 'In a bowl, mix flour, baking powder, sugar, and salt.'),
(6, 2, 'In another bowl, whisk milk, eggs, and melted butter.'),
(6, 3, 'Combine wet and dry ingredients and stir until smooth.'),
(6, 4, 'Cook pancakes on a griddle until bubbles form, then flip and cook until golden brown.'),
(7, 1, 'Cook sushi rice according to package instructions and cool.'),
(7, 2, 'Place nori sheets on a bamboo mat and spread rice evenly on top.'),
(7, 3, 'Place slices of fish, cucumber, and avocado on rice.'),
(7, 4, 'Roll tightly and slice into pieces.'),
(8, 1, 'Heat oil in a pan and add bell peppers, broccoli, and carrots.'),
(8, 2, 'Stir-fry vegetables until tender.'),
(8, 3, 'Add soy sauce and minced garlic, cook for an additional 2 minutes.'),
(9, 1, 'Preheat oven to 350°F.'),
(9, 2, 'Mix flour, cocoa powder, sugar, and baking powder.'),
(9, 3, 'Add eggs and melted butter, and mix until smooth.'),
(9, 4, 'Pour batter into a greased pan and bake for 30 minutes.'),
(10, 1, 'Preheat oven to 300°F.'),
(10, 2, 'Rub ribs with garlic powder and paprika.'),
(10, 3, 'Coat with BBQ sauce and bake for 2 hours.'),
(11, 1, 'Chop cucumber, cherry tomatoes, and Kalamata olives.'),
(11, 2, 'Combine with feta cheese and mix well.'),
(12, 1, 'Marinate chicken in lemon juice, garlic, and olive oil for 30 minutes.'),
(12, 2, 'Grill chicken until cooked through.'),
(12, 3, 'Serve with your choice of sides.'),
(13, 1, 'Season fish with salt and pepper.'),
(13, 2, 'Cook in a hot skillet for 3-4 minutes per side.'),
(13, 3, 'Assemble tacos with cooked fish, shredded cabbage, and zesty sauce.'),
(14, 1, 'Preheat oven to 375°F.'),
(14, 2, 'Slice eggplant and layer in a baking dish.'),
(14, 3, 'Top with marinara sauce and cheese, then bake for 45 minutes.'),
(15, 1, 'Marinate chicken in teriyaki sauce for 30 minutes.'),
(15, 2, 'Grill chicken and sprinkle with sesame seeds before serving.'),
(16, 1, 'Cook ground beef with marinara sauce and seasonings.'),
(16, 2, 'Layer meat sauce, ricotta cheese, mozzarella cheese, and lasagna noodles in a baking dish.'),
(16, 3, 'Bake for 60 minutes at 375°F.'),
(17, 1, 'Slice tomatoes and fresh mozzarella.'),
(17, 2, 'Arrange on a plate and top with fresh basil leaves.'),
(17, 3, 'Drizzle with olive oil and balsamic vinegar.'),
(18, 1, 'Cook rice noodles according to package instructions.'),
(18, 2, 'Stir-fry shrimp with bean sprouts and vegetables.'),
(18, 3, 'Add cooked noodles and sauce, stir well.'),
(19, 1, 'Preheat oven to 375°F.'),
(19, 2, 'Season salmon with lemon and dill.'),
(19, 3, 'Bake for 20 minutes or until flaky.'),
(20, 1, 'Mash bananas in a bowl.'),
(20, 2, 'Mix with flour, sugar, butter, and baking soda.'),
(20, 3, 'Pour into a greased loaf pan and bake for 60 minutes at 350°F.'),
(21, 1, 'Cook chicken with curry powder until browned.'),
(21, 2, 'Add coconut milk and simmer until chicken is cooked through.'),
(21, 3, 'Serve over rice.'),
(22, 1, 'Simmer shrimp with lemongrass and chili paste.'),
(22, 2, 'Add mushrooms and cook until tender.'),
(22, 3, 'Serve hot with fresh cilantro.'),
(23, 1, 'Blend chickpeas, tahini, garlic, and cumin until smooth.'),
(23, 2, 'Serve with pita bread and vegetables.'),
(24, 1, 'Cook beef sirloin with mushrooms and onions.'),
(24, 2, 'Add beef broth and simmer.'),
(24, 3, 'Stir in sour cream and serve over noodles.'),
(25, 1, 'Cook Arborio rice in chicken broth, stirring frequently.'),
(25, 2, 'Add sautéed mushrooms and Parmesan cheese.'),
(25, 3, 'Stir until creamy and well combined.'),
(26, 1, 'Cook chicken with fajita seasoning.'),
(26, 2, 'Sauté bell peppers and onions.'),
(26, 3, 'Serve chicken and vegetables in tortillas.'),
(27, 1, 'Mix cornmeal, flour, sugar, and baking powder.'),
(27, 2, 'Add milk and stir until smooth.'),
(27, 3, 'Bake in a greased pan for 25 minutes at 375°F.'),
(28, 1, 'Preheat oven to 425°F.'),
(28, 2, 'Prepare pie crust and fill with spiced apple slices.'),
(28, 3, 'Bake for 45 minutes until crust is golden.'),
(29, 1, 'Prepare duck and coat with Peking duck sauce.'),
(29, 2, 'Roast duck in a preheated oven at 375°F for 90 minutes.'),
(30, 1, 'Prepare pie crust and fill with spiced apple slices.'),
(30, 2, 'Bake for 60 minutes at 425°F until crust is golden.');

INSERT INTO Comments (recipe_id, user_id, comment) VALUES
(1, 1, 'Delicious! My family loved it.'),
(1, 2, 'A bit rich for my taste, but good.'),
(2, 3, 'Perfect salad for a summer day!'),
(2, 4, 'Fresh and light, just what I needed.'),
(3, 1, 'Rich and creamy, the mushrooms add a nice touch.'),
(3, 2, 'One of my favorite comfort foods.'),
(4, 3, 'Tacos turned out great, easy recipe.'),
(4, 4, 'Love the flavor, but I added extra toppings.'),
(5, 1, 'Classic pizza, always a hit.'),
(5, 2, 'Great recipe, but I added some olives.'),
(6, 3, 'Fluffy and delicious pancakes, my kids love them.'),
(6, 4, 'Perfect breakfast treat, easy to make.'),
(7, 1, 'Sushi rolls turned out fantastic, will make again.'),
(7, 2, 'A bit tricky but worth it, fresh and tasty.'),
(8, 3, 'Quick and healthy, a great side dish.'),
(8, 4, 'Add some chili flakes for extra kick.'),
(9, 1, 'Rich chocolate cake, perfect for parties.'),
(9, 2, 'Loved the texture, but too sweet for my taste.'),
(10, 3, 'BBQ ribs were tender and flavorful, a real treat.'),
(10, 4, 'Took longer than expected but worth it.'),
(11, 1, 'Great salad, perfect for summer.'),
(11, 2, 'Very refreshing, but could use more feta.'),
(12, 3, 'The lemon and garlic make this dish fantastic.'),
(12, 4, 'Simple yet flavorful, a new favorite.'),
(13, 1, 'Fish tacos were light and delicious.'),
(13, 2, 'Nice and fresh, but I added some avocado.'),
(14, 3, 'Eggplant Parmesan was hearty and satisfying.'),
(14, 4, 'Great recipe, but I reduced the cheese a bit.'),
(15, 1, 'Teriyaki chicken was perfectly seasoned.'),
(15, 2, 'Simple and tasty, will definitely make again.'),
(16, 3, 'Classic lasagna, very comforting.'),
(16, 4, 'Great recipe, though I added more cheese.'),
(17, 1, 'Caprese salad is always a winner.'),
(17, 2, 'Perfectly balanced flavors, easy to make.'),
(18, 3, 'Pad Thai was delicious and flavorful.'),
(18, 4, 'A bit too spicy, but still good.'),
(19, 1, 'Baked salmon was tender and flavorful.'),
(19, 2, 'Simple yet tasty, loved the lemon.'),
(20, 3, 'Banana bread was moist and flavorful.'),
(20, 4, 'Great texture, but added some nuts.'),
(21, 1, 'Chicken curry was rich and satisfying.'),
(21, 2, 'Delicious and easy, will make it again.'),
(22, 3, 'Tom Yum soup was spicy and flavorful.'),
(22, 4, 'Could use more lemongrass, but still great.'),
(23, 1, 'Falafel was crispy and tasty, loved the tahini.'),
(23, 2, 'A bit dry, but overall good.'),
(24, 1, 'Beef Stroganoff was creamy and comforting.'),
(24, 2, 'Loved the richness of the sauce.'),
(25, 1, 'Mushroom risotto was creamy and delicious.'),
(25, 2, 'Perfectly cooked, will make again.'),
(26, 1, 'Chicken fajitas were flavorful and easy to make.'),
(26, 2, 'Great recipe, but I used whole wheat tortillas.'),
(27, 1, 'Cornbread was sweet and moist.'),
(27, 2, 'Perfect side dish for chili.'),
(28, 1, 'Apple pie was classic and delicious.'),
(28, 2, 'Great crust and filling, loved it.'),
(29, 1, 'Peking duck was crispy and flavorful.'),
(29, 2, 'A bit involved but worth the effort.'),
(30, 1, 'Apple pie was perfect, just like Grandma’s.'),
(30, 2, 'Delicious and classic, a real treat.');

INSERT INTO Ratings (recipe_id, user_id, rating) VALUES
(1, 1, 5),
(1, 2, 4),
(2, 3, 5),
(2, 4, 5),
(3, 1, 4),
(3, 2, 5),
(4, 3, 4),
(4, 4, 4),
(5, 1, 5),
(5, 2, 4),
(6, 3, 5),
(6, 4, 5),
(7, 1, 4),
(7, 2, 4),
(8, 3, 4),
(8, 4, 4),
(9, 1, 5),
(9, 2, 4),
(10, 3, 5),
(10, 4, 4),
(11, 1, 5),
(11, 2, 4),
(12, 3, 5),
(12, 4, 5),
(13, 1, 4),
(13, 2, 4),
(14, 3, 4),
(14, 4, 4),
(15, 1, 4),
(15, 2, 4),
(16, 3, 5),
(16, 4, 4),
(17, 1, 5),
(17, 2, 5),
(18, 3, 4),
(18, 4, 4),
(19, 1, 5),
(19, 2, 4),
(20, 3, 5),
(20, 4, 4),
(21, 1, 5),
(21, 2, 5),
(22, 3, 4),
(22, 4, 4),
(23, 1, 4),
(23, 2, 3),
(24, 1, 5),
(24, 2, 4),
(25, 1, 5),
(25, 2, 5),
(26, 1, 4),
(26, 2, 4),
(27, 1, 5),
(27, 2, 4),
(28, 1, 5),
(28, 2, 5),
(29, 1, 5),
(29, 2, 4),
(30, 1, 5),
(30, 2, 5);

INSERT INTO Favorites (user_id, recipe_id) VALUES
(1, 1),
(1, 3),
(1, 5),
(2, 2),
(2, 7),
(2, 8),
(3, 4),
(3, 6),
(3, 9),
(4, 10),
(4, 11),
(4, 13),
(5, 12),
(5, 14),
(5, 15),
(1, 16),
(1, 17),
(1, 18),
(2, 19),
(2, 20),
(2, 21),
(3, 22),
(3, 23),
(3, 24),
(4, 25),
(4, 26),
(4, 27),
(5, 28),
(5, 29),
(5, 30);

